[general]
import = ["themes/tokyonight-night.toml"]
live_config_reload = true

[window]
padding = { x = 8, y = 8 }
dynamic_padding = true
option_as_alt = "Both"
decorations = "None"
decorations_theme_variant = "Dark"

[scrolling]
history = 50000
multiplier = 5

[font]
size = 12
offset = { x = 0, y = 4 }
builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }
blink_interval = 500
blink_timeout = 0
unfocused_hollow = true
thickness = 0.2

[mouse]
hide_when_typing = true

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\\u0000-\\u001F\\u007F-\\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"