[general]
import = ["themes/tokyonight-night.toml"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
decorations = "none"
opacity = 1.0
blur = false
option_as_alt = "Both"

[scrolling]
history = 50000

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font]
size = 12

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }
blink_interval = 500
blink_timeout = 0

[mouse]
hide_when_typing = true
