require "plugins.launch"

spec "plugins.colorscheme"
spec "plugins.treesitter"
spec "plugins.surround"
spec "plugins.comment"
spec "plugins.illuminate"
spec "plugins.neoscroll"
spec "plugins.fidget"
spec "plugins.breadcrumbs"
spec "plugins.gitsigns"
spec "plugins.nvimtree"
spec "plugins.lualine"
spec "plugins.telescope"
spec "plugins.trouble"
spec "plugins.todo-comments"
spec "plugins.cmp"
spec "plugins.autopairs"

spec "lsp.mason"
spec "lsp.lspconfig"
spec "lsp.none-ls"

require "plugins.lazy"
