require "plugins.launch"

spec "plugins.colorscheme"
spec "plugins.treesitter"
spec "plugins.surround"
spec "plugins.comment"
spec "plugins.illuminate"
spec "plugins.neoscroll"
spec "plugins.fidget"
spec "plugins.lualine"
spec "plugins.autopairs"
spec "plugins.alternate-toggler"
spec "plugins.indent-blankline"
spec "plugins.gitsigns"
spec "plugins.codewindow"
spec "plugins.trouble"
spec "plugins.todo-comments"
spec "plugins.telescope"
spec "plugins.auto-session"
spec "plugins.cmp"
spec "plugins.mason"
spec "plugins.nvim-lint"
spec "plugins.conform"
spec "lsp.lspconfig"
spec "plugins.typescript-tools"

require "plugins.lazy"
